const ROUTES = {
  DERA: {
    STACK_NAVIGATOR: "DeraStackNavigator",
    TAB_NAVIGATOR: "DeraTabNavigator",
    // HOME SCREENS
    HOME: "HomeScreen",
    SCHEDULE: "ScheduleScreen",
    CHATS: "ChatsScreen",
    NOTIFICATIONS: "NotificationsScreen",
    SETTINGS: "SettingsScreen",
    // DAIRY PRODUCT SCREENS
    ADD_DAIRY_PRODUCT: "AddDairyProductScreen",
    EDIT_DAIRY_PRODUCT: "EditDairyProductScreen",
    VIEW_DAIRY_PRODUCT: "ViewDairyProductScreen",
    SHOW_DAIRY_PRODUCTS: "ShowDairyProductsScreen",
    // LIVESTOCK PRODUCT SCREENS
    ADD_LIVESTOCK: "AddLivestockScreen",
    EDIT_LIVESTOCK: "EditLivestockScreen",
    SHOW_LIVESTOCKS: "ShowLivestocksScreen",
    VIEW_LIVESTOCK: "ViewLivestockScreen",
    LIVESTOCK_FEATURES: "LivestockFeaturesScreen",
    LIVESTOCK_PHOTOS: "LivestockPhotosScreen",
    SELECT_CONSUMER: "SelectConsumerScreen",
    // DVM SERVICES SCREENS
    VIEW_DVM_PROFILE: 'ViewDvmProfileScreen',
    VIEW_DVM_SERVICE: 'ViewDvmServiceScreen',
    SHOW_DVM_SERVICES: 'ShowDvmServicesScreen',
    // SETTINGS SCREENS
    EDIT_ACCOUNT_INFO: "EditAccountInfoScreen",
    LOCATION_AND_ADDRESS: "LocationAndAddressScreen",
    MANAGE_BANNER_PHOTOS: "ManageBannerPhotosScreen",
    PAYMENT_WALLETS: "PaymentWalletsScreen",
    SOCIAL_MEDIA_HANDLES: "SocialMediaHandlesScreen",
    DAIRY_PRODUCT_ORDERS: "DairyProductOrdersScreen",
    LIVESTOCK_SOLD_OUT: "LivestockSoldOutScreen",
    DVM_APPOINTMENTS: 'DvmAppointmentsScreen',
    DVM_APPOINTMENT_DETAILS: 'DvmAppointmentDetailsScreen',
    NOTIFICATION_DETAILS: 'NotificationDetailsScreen',
    SCHEDULE_DETAILS: 'ScheduleDetailsScreen',
    QR_CODE_SCAN: 'QrCodeScanScreen',
    DEMO_CONFIG: "DemoConfigScreen",
  },
  DVM: {
    STACK_NAVIGATOR: "DvmStackNavigator",
    TAB_NAVIGATOR: "DvmTabNavigator",
    // HOME SCREENS
    HOME: "Home",
    APPOINTMENTS: 'AppointmentsScreen',
    CHATS: 'ChatsScreen',
    NOTIFICATIONS: 'NotificationsScreen',
    SETTINGS: 'SettingsScreen',
    // SERVICES SCREENS
    ADD_SERVICE: 'AddServiceScreen',
    EDIT_SERVICE: 'EditServiceScreen',
    SHOW_SERVICES: 'ShowServicesScreen',
    VIEW_SERVICE: 'ViewServiceScreen',
    // APPOINTMENT SCREENS
    VIEW_APPOINTMENT_DETAILS: 'ViewAppointmentDetailsScreen',
    VIEW_DERA_PROFILE: 'ViewDeraProfileScreen',
    // SETTINGS SCREEN 
    EDIT_ACCOUNT_INFO: 'EditAccountInfoScreen',
    LOCATION_AND_ADDRESS: "LocationAndAddressScreen",
    PAYMENT_WALLETS: "PaymentWalletsScreen",
    SOCIAL_MEDIA_HANDLES: "SocialMediaHandlesScreen",
    APPOINTMENTS_HISTORY: 'AppointmentsHistoryScreen',
  },
  CONSUMER: {
    STACK_NAVIGATOR: 'ConsumerStackNavigator',
    TAB_NAVIGATOR: 'ConsumerTabNavigator',
    // HOME SCREENS
    HOME: 'Home',
    SCHEDULES: 'SchedulesScreen',
    CHATS: 'ChatsScreen',
    NOTIFICATIONS: 'NotificationsScreen',
    SETTINGS: 'SettingsScreen',
    // SETTINGS SCREENS
    EDIT_ACCOUNT_INFO: 'EditAccountInfoScreen',
    LOCATION_AND_ADDRESS: "LocationAndAddressScreen",
    DAIRY_PRODUCT_ORDERS: "DairyProductOrdersScreen",
    LIVESTOCK_PRODUCT_ORDERS: "LivestockProductOrdersScreen",
    SHOW_DAIRY_PRODUCTS: 'ShowDairyProductScreen',
    VIEW_DAIRY_PRODUCT: 'ViewDairyProductScreen',
    SHOW_DAIRY_PRODUCTS: 'ShowDairyProductsScreen',
    VIEW_DAIRY_PRODUCT: 'ViewDairyProductScreen',
    SHOW_LIVESTOCKS: 'ShowLivestocksScreen',
    VIEW_LIVESTOCK: 'ViewLivestockScreen',
    VIEW_DERA_PROFILE: 'ViewDeraProfileScreen',
    PLACE_ORDER_NOW: 'PlaceOrderNowScreen',
    SCHEDULE_DETAILS: 'ScheduleDetailsScreen',
    QR_CODE: 'QRCodeScreen',
    LIVESTOCK_HISTORY: 'LivestockHistoryScreen',
  },
  COMMON: {
    SPLASH: "Splash",
    LOGIN: "Login",
    REGISTER: "Register",
    RESET_PASSWORD: "ResetPassword",
    ADDITIONAL_INFORMATION: "AdditionalInformation",
    OTP: "OneTimePassword",
    CHAT_SCREEN: "ChatScreen",
    SUBMIT_QUERY: "SubmitQueryScreen",
    ADMIN_NOTIFICATION: "AdminNotificationScreen",
  },
}

export default ROUTES